---
- meta: flush_handlers

- name: Copy the initialization script to tmp
  template:
    src: replicaset_init.j2
    dest: /tmp/replicaset_init.js
- name: Copy the initialization script to tmp
  template:
    src: db_admin_user.j2
    dest: /tmp/db_admin_user.js

- name: Create Admin User
  shell: sleep 60 && mongo localhost:{{ item.port }}/admin  < /tmp/db_admin_user.js
  ignore_errors: yes
  with_items: "{{ mongo_databases }}"



- name: Execute the initialization script and add all replicants
  shell: sleep 60 && mongo localhost:{{ item.port }}/admin -u {{ mongo_admin_user }} -p {{ mongo_admin_pass }} --authenticationDatabase admin < /tmp/replicaset_init.js
  ignore_errors: yes
  with_items: "{{ mongo_databases }}"

- name: play that sets a group to loop over
  vars:
    mongo_replicas: "{{ groups['mongo_secondaries_servers'] }}"
  template:
    src: replicaset_add_node.j2
    dest: /tmp/replicaset_add_node.js

- name: Execute the initialization script and add all replicants
  shell: mongo --host localhost:{{ item.port }} -u {{ mongo_admin_user }} -p {{ mongo_admin_pass }} --authenticationDatabase admin < /tmp/replicaset_add_node.js
  with_items: "{{ mongo_databases }}"

  # ignore_errors: no



